name: Daily Fear and Greed Task

on:
  push:
    branches:
      - master
      - main
  # Runs on 52min 2200, 2300, 0000, for monday to friday
  schedule:
    - cron: '52 13,14,15 * * 1-5' 

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Change if you need different version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      # Installing Depency  
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/fear_and_greed.py
